#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $SkyHawkuserbot_REPO == "SkyHawk" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0hhcnNoLTc4L0RhcmtfdXNlcmJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $SkyHawkuserbot_REPO == "Skyhawk" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0hhcnNoLTc4L0RhcmtfdXNlcmJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $SkyHawkuserbot_REPO =~ $regex ]]
    then
        if [[ $SkyHawkuserbot_REPO_BRANCH ]]
        then
            echo "${SkyHawkuserbot_REPO}/archive/${SkyHawkuserbot_REPO_BRANCH}.zip"
        else
            echo "${SkyHawkuserbot_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0hhcnNoLTc4L0RhcmtfdXNlcmJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="skyhawk.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    SkyHawkuserbotPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $SkyHawkuserbotPATH
    echo "    Starting Skyhawk bot    "
    echo "
    ┈┈┈╲┈┈┈┈╱
┈┈╱▔▔▔▔╲
┈┈┃┈▇┈┈▇┈┃
╭╮┣━━━━━━┫╭╮
┃┃┃┈┈┈┈┈┈┃┃┃
╰╯┃┈┈┈┈┈┈┃╰╯
┈┈╰┓┏━━┓┏╯
┈┈┈╰╯┈┈╰╯


    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
